spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  security:
    oauth2:
      # JWT decoder configured manually in SecurityConfig
      client:
        registration:
          obo-generic:
            provider: sts
            client-id: gateway-service
            client-secret: secret-gateway
            authorization-grant-type: urn:ietf:params:oauth:grant-type:token-exchange

server:
  port: 8080

logging:
  level:
    com.example.obo: DEBUG
    org.springframework.security: DEBUG

