spring:
  profiles:
    active: dev
  application:
    name: downstream-service-c
  security:
    oauth2:
      # JWT decoder configured manually in SecurityConfig

server:
  port: 8080

grpc:
  server:
    port: 9090

logging:
  level:
    com.example.obo: DEBUG
    org.springframework.security: DEBUG

