spring:
  profiles:
    active: dev
  application:
    name: downstream-service-c
  security:
    oauth2:
      client:
        registration:
          obo-generic:
            provider: sts
            client-id: downstream-service-c
            client-authentication-method: none
            authorization-grant-type: urn:ietf:params:oauth:grant-type:token-exchange
        provider:
          sts:
            token-uri: http://idp-service.idp-namespace.svc.cluster.local/oauth2/token

server:
  port: 8080

grpc:
  server:
    port: 9090

logging:
  level:
    com.example.obo: DEBUG
    org.springframework.security: DEBUG

